#!/usr/bin/python
import re
G =['\033[38;5;022m ','\033[38;5;028m ','\033[38;5;034m ','\033[38;5;040m ',
    '\033[38;5;046m ','\033[38;5;047m ']
RX = ['\ ([0-2][0-9a-fA-F])','\ ([3-5][0-9a-fA-F])','\ ([6-8][0-9a-fA-F])',
      '\ ([9a-bA-B][0-9a-fA-F])','\ ([c-eC-E][0-9a-fA-F])','\ ([d-fD-F][0-9a-fA-F])']
RS ='\033[0;0m'
while 1:
    try:
        input = raw_input()
        for i in range(0,6):
            input = re.sub(RX[i], G[i]+r'\1'+RS, input, count=16)
        print input
    except:
        quit()
